### PR TITLE
Implemented general wrap lines feature

### PR DESCRIPTION
**Pull request by vaibhavbhat16**
Implemented general wrap lines feature

### CODE REVIEW

**Comment by ilanbiala** [comment]
@NikhilKalige merge please.

**Comment by albertorestifo** [comment]
This PR needs to be updated with the latest Atom API

**Comment by MoritzKn** [comment]
Thanks for your PR but honestly I don't know why Docblockr needs a general wrap line, function since Docblockr is devoted to make wiring *comments* easier.
@nikhilkalige veto?

Despite that -- as mentioned by @albertorestifo -- this needs to be updated to the current Atom API.

**Comment by MoritzKn** [comment]
@vaibhavbhat16 If this isn't long resolved, maybe take a look at [wrap-lines](https://atom.io/packages/wrap-lines).

**Pull request closed without merging**
