### PR TITLE
Add parse_var methode to the RustParser

### PR DESCRIPTION
**Pull request by MoritzKn**
This will prevent an error, when using block comments.

### CODE REVIEW

**Comment by nikhilkalige** [comment]
Can you  please me add tests to the rust parser

**Comment by MoritzKn** [comment]
I don't really know how... As far as I can see the project has no system in place for such tests. Shouldn't this be the first thing to add?

**Comment by nikhilkalige** [comment]
Please check the develop branch, I have made an attempt at adding some
tests.

**Comment by MoritzKn** [comment]
Ok my fault, I've overlooked this branch.
Can you give me an short explanation of how to run the tests or at maybe just me in the right direction?
I've tried to run the `runner.js` and `language.spec.js` with mocha, but I don't works because of the es2015 code (`import` stements, etc..). I guess I have to use babel somohow, but I have no idea how to use mocha and babel together.

**Comment by nikhilkalige** [comment]
Just run using atom -t docblockr/spec from the command line in the
.atom/packages folder

**Comment by MoritzKn** [comment]
It works that way, but It doesn't seems like any tests are executed.
Here is the output if I run `atom -t docblockr/spec`:
```
~/.atom/packages$ atom -t docblockr/spec
[12343:0719/130257:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[12343:0719/130258:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[12343:0719/130258:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[12343:0719/130258:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[12343:0719/130258:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[12343:0719/130258:INFO:audio_manager_pulse.cc(174)] Not implemented!
[12343:0719/130258:INFO:audio_manager_pulse.cc(174)] Not implemented!
[12343:0719/130258:INFO:audio_manager_pulse.cc(174)] Not implemented!

  0 passing (2ms)

Window load time: 554ms
```

**Comment by nikhilkalige** [comment]
Can you push ur branch

**Comment by MoritzKn** [comment]
So far I didn't written any tests.
But here it is: https://github.com/MoritzKn/docblockr/tree/feature/fix-rust-block-comment

**Comment by nikhilkalige** [comment]
I think the reason is that you merged an old branch of develop.. can you try with the updated one... Please use `develop` rather than `feature/spec` sorry about that confusion..

**Comment by MoritzKn** [comment]
Ok thanks, it works on the develop branch.

**Comment by MoritzKn** [comment]
I've had to make some more fixes at the RustParser itself to make it work, but I also added a bunch of tests.

**Comment by nikhilkalige** [comment]
@MoritzKn I will get that merged.. So I just wanted to know your thoughts on the test method we are using. Do you think it would make sense to have on more level of dataset to test for `DocsParser.prototype.parse` so we could have a file
```
lang: js

var a = 10
/**
 * [a description]
 * @type {Number}
 */

etc...
```

**Comment by MoritzKn** [comment]
I think since the methods on the DocsParser.prototype inherit to the individual parsers, we could tests these methods with the existing datasets.

**Pull request merged**
