### PR TITLE
add some basic es6 syntax detection

### PR DESCRIPTION
**Pull request by malko**
Add support for es6 generators, class methods, getter and setter.
address issue #36 and #64 partially.

### CODE REVIEW

**Comment by malko** [comment]
Hi,
I can see that merge request are long to be accepted, do you need help to maintain this atom package ?
If so i'm ok to help you with maintenance of this repository and publication of the atom package.

I can will update my merge request to work with the latest version but hope it wil be merged soon this time or i will be forced to either jump to another atom package or fork yours.

Hope to read from you soon

**Comment by NikhilKalige** [comment]
@malko Sorry about the pending merge's. I would love have some help in maintaining it.. Let me know if you are still interested.

**Comment by malko** [comment]
@NikhilKalige dont be sorry, I totally understand that maintaining a package may be time consuming. I use your package and so i'm ok to help you on this.

**Comment by malko** [comment]
thank you for adding me to the repo will try to do my best ;)

**Pull request closed without merging**
