### PR TITLE
Do some basic rust parsing of functions

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
First off I apologise for my poor javascript. Not my native language.

Here I add a simple extension to add rust parsing of functions and formatting the output.

The formatted output tries to adhere to the format recommended by the [rust book](https://doc.rust-lang.org/rust-by-example/meta/doc.html) and the machine readable [specs](https://deterministic.space/machine-readable-inline-markdown-code-cocumentation.html)

Comments, suggests, outright crying over poor js code blasphemys are expected and encouraged.

Fixes: #331 
Fixes: #347

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
I only seem to have it working on the docblockr:parse-tab command and not the docblockr:parse-enter, I am looking into it but suggestions would be welcome

**Comment by QuantumEntangledAndy** [comment]
Ok the reason `'extend_line': /^\s*(\/\/[\/!]?|#)/` for rust was not working in rust is because the scope is `comment.block` but the original code explicitly checked for `comment.line` I have pushed a fix on that too

**Comment by MoritzKn** [comment]
First of all, thanks for your time! Please be aware though: this package, as most of the atom eco-system, is unfortunately pretty much unmaintained.
That being said if you are confident with your PR, I'd be willing to simply merge it. But if you need someone to review your work and/or help you with testing, you would need to find someone by yourself.

Please make sure that:
- the code is properly tested
- includes specs / automated tests
- debug logs / console.log are removed
- code is properly formated (whitespace, indention)

**Comment by QuantumEntangledAndy** [comment]
Yes I figured this might be unmaintained when looking at the commit histories. Just thought I'd share the changes that got it working for me.

- Testing has been done by me in rust on my own project and its holding up fine
- No specs/tests so I will look into adding that later in the week when I've got time
- Logs should be all removed but I'll double check
- I will double check the white space and maybe it though a formatter aswell

**Comment by QuantumEntangledAndy** [comment]
@MoritzKn I've gone and added the specs and have improved the rust parser to match more edge cases. I think it should be ok to merge now if you want to give it a once over.


- [x]    the code is properly tested
- [x]    includes specs / automated tests
- [x]    debug logs / console.log are removed
- [x]    code is properly formated (whitespace, indention) (via JS Beautify)

**Comment by MoritzKn** [comment]
Hi @QuantumEntangledAndy I was just getting ready to merge your PR. You've got to know I've literally didn't touch this repo in years. The thing is... the last person that worked on Docblockr was @Fluvf who did amazing work and a _lot_ of cleaning up. I merged all of it into `develop` but we never got around to making a release or merging into `master`. So now we have a _bunch_ of changes sitting in `develop` that I don't want to throw away.

The issue is if I merge your changes into `master` we can no longer merge `develop`. Would you mind rebasing (or merging) your changes against `develop`?

**Comment by QuantumEntangledAndy** [comment]
Sure I'll check out that branch and try a rebase. It's getting late where I am so that will have to be tomorrow now.

**Comment by QuantumEntangledAndy** [comment]
So I have a rebase ready do you want me to repoint this PR into the develop branch?

**Comment by MoritzKn** [comment]
Yes sure, you can change to the target branch. But I can do that too so it's not so important.

**Comment by QuantumEntangledAndy** [comment]
Ok done and ready

**Comment by QuantumEntangledAndy** [comment]
Ok I just saw that there was a new setting in develop that makes return and prameter doc string optional so I made a quick edit to include that in rust too :)

**Comment by QuantumEntangledAndy** [comment]
Awesome thanks for getting the merged :)

**Comment by QuantumEntangledAndy** [comment]
If you have any rusted related issues feel free to drop me an email or something

**Comment by MoritzKn** [comment]
I can't really believe it but after over 3 years I've actually just pushed a new release to the atom package registry, enjoy!

**Comment by MoritzKn** [comment]
That'd be awesome

**Pull request merged**
