### PR TITLE
update javascript functionRegex to test for es-next syntax (#203)

### PR DESCRIPTION
**Pull request by jwhitmarsh**
now checks for:
- async
- export
- default

<body>

<footer>

### CODE REVIEW

**Comment by MoritzKn** [comment]
First of all: Thanks for you RP!
But could you please tweak a few things:

- Add test cases. See tests.md for more Information
- Change `\\s` to `\\s+` to allow multiple spaces
- Force `export` to be the first key word, so that thins like `default export function foo() {` won't work

**Comment by jwhitmarsh** [comment]
Thanks :)

Just working on those now - sorry for newbie question, what's the best way to run the tests when I'm developing? `./spec/atom-build-package.sh` looks like it's setup to work for Travis, rather than running locally?

**Comment by MoritzKn** [comment]
NP, I asked the same question a week ago ;)
Just run `atom -t docblockr/spec` from your package folder (`~/.atom/packages/` if your on Linux or OSX   too I guess).

**Comment by jwhitmarsh** [comment]
Committed :)

I've added tests for the function parsing, but can't see how to do it for `get_function_return_type` because it looks like the tests are setup to only ever pass one argument (and the method expects two) - have I misunderstood that?

**Comment by MoritzKn** [comment]
A few more few things:
* Please introduce non matching groups with `:?` like this `(:?default\s+)?`
* You missed one `\\s+` after `default`
* Don't mark optional stuff by using a star (`*`), use `?` instead please
   Only use a star if something should be optional and repeatable
* Move the checks for `export` and `default` to the `preFunction` regex.  
  This will allow for things like `export const add = n => n + 1`
* Is there a reason why you used `||` instead of `|` a few times ?
* `function(\\*|\\s+\\*)?` should be simplified to `function(:?\\s*\\*)?`  
  writing generator functions like `function *foo() {` still won't work, but that is not your problem
* Why do you include `\*` in here `/\basync\b|\*/.test(line) ? 'Promise' : null`?
  - Generator functions return an Iterator not a `Promise`
  - `*` can occur at multiple positions take `function foo(bar='*') {` for example.
* I don't really like the why you are detecting if a function is async. Code like `function foo(async) {` won't work... maybe you could try to use a capture inside the regular regex

Sorry for being so *extremely* nitpicky, but the parsers are sensitive code and already caused a bunch of errors.

**To the tests:**
I am happy with your tests, but please extend them if you change your code corresponding to the points above.


> [...] but can't see how to do it for get_function_return_type because it looks like the tests are setup to only ever pass one argument (and the method expects two) - have I misunderstood that?

No, you are right, that is a problem.
The test setup is fairly new and still somewhat work in progress. I will add some way to test functions with multiple parameters.

**Comment by MoritzKn** [comment]
I added a way to test functions with multiple arguments: just use an array.
See: [fa70e34](https://github.com/nikhilkalige/docblockr/commit/adb6c9fbc9dc0cd1b69c7872318504f515e86509)

**Comment by jwhitmarsh** [comment]
Apologies for the delay with this, I had a long weekend away. 

I've tried to neaten this up a lot - no need to apologies about picking up on the issues! I feel bad that there was so much to pick on. Hopefully this is getting closer to what's required.

**Comment by MoritzKn** [comment]
I will take some time and review this later, but one thing already caught my attention:
`export` and `default` should be the very first thing, otherwise code like this won't work:
```js
export default const foo = function bar(a, b, c) {
```

**Comment by jwhitmarsh** [comment]
I've pushed a commit to fix that, have you had a chance to review?

**Comment by MoritzKn** [comment]
Not yet, sorry. I will try to review it today.

**Comment by MoritzKn** [comment]
Perfect, I have nothing to complain about :)

**Comment by MoritzKn** [comment]
Just released version 0.8.4 which contains all you all you enhancements. 
Thank you for your effort!

**Comment by jwhitmarsh** [comment]
Awesome, thank you for helping out so much with that!

**Pull request merged**
