### PR TITLE
Migrate to `class` syntax throughout the project

### PR DESCRIPTION
**Pull request by DevBonBon**
Also contains some slight cleanup that was possible after the change.
See commit messages for details.

I'll do one more pull request after this, with some general cleanup before I start working on the customizability feature (which will probably result in a non backwards compatible version).
It'll also fix all the bugs I can find.

Sorry these pull requests are a bit too general, and not focused on just one change. Just let me know and I'll split these up into multiple ones.
I'm hoping this makes it faster overall, not having to go through ~10 different pull requests.

### CODE REVIEW

**Comment by DevBonBon** [comment]
I updated the pull request. It had too many unrelated changes hidden in single commits.

**Comment by MoritzKn** [comment]
Is this ready to be merged? Are you confident you didn't break anything?

**Comment by DevBonBon** [comment]
It is. I don't think anythings broken, but deep tag alignment is a bit over active. I think it's bugged in master and now somehow got fixed as I haven't touched the logic.
This pull request with per section indent off:
```
/**
 * [parseCommand description]
 *
 * @param   {[type]} event                       [description]
 * @param   {[type]} inline                      [description]
 * @returns {[type]}               [description]
 * @throws  {[type]} [description]
 * @example
 * @todo    [code]
 */
```
master:
```
/**
 * [parse_command description]
 *
 * @param   {[type]} event         [description]
 * @param   {[type]} inline        [description]
 * @returns {[type]}               [description]
 * @throws  {[type]} [description]
 * @example
 * @todo    [code]
 */
```
I plan on addressing it in the next pull request, alongside with a punch of other bugs.

**Comment by MoritzKn** [comment]
Ok great 👍 
If you fix bugs, please make sure to check the issue tracker and see if they where already reported. Maybe we can also reduce the number of open issues with your affords. I can see how much work you are putting into this, it is highly appreciated.

**Pull request merged**
