### PR TITLE
Added support for PHP7 return value

### PR DESCRIPTION
**Pull request by Cronos87**

### CODE REVIEW

**Comment by kitbrennan90** [comment]
@nikhilkalige or @MoritzKn - any chance of this being merged? 

Return types are fast becoming common place so it'd be awesome for DocBlockr to support them 👍

**Comment by MoritzKn** [comment]
Thanks for your PR!
I am a little bit unhappy with the fact that this uses the return *value* (`retval`) to bypass the return *type*.
Could you please use `options` instead?

**Comment by Cronos87** [comment]
Hello. Sure! I'll do it today. Thanks for the reply.

**Comment by MoritzKn** [comment]
Actually most languages (c++ and Java) do the same, so I would be find with this approve too.

**Comment by Cronos87** [comment]
As you wish. I was looking at the C++ and Java codes to change my code. But if you're OK with this, it's perfect.
I'll update it anyway, as PHP 7.1 added the return type void.

**Comment by Cronos87** [comment]
Is it fine like this?

**Comment by MoritzKn** [comment]
Seams to work, except one thing:
```php
/**<enter>
function foo()  :bar{
}
```
results in
```php
/**
 * [foo description]
 * @return bar{ [description]
 */
function foo()  :bar{
}
```

Please change `\\S` to an actual type name regex.

**Comment by Cronos87** [comment]
Sorry, my bad... I'll fix it as soon as possible.

**Comment by Cronos87** [comment]
I changed the regex, but this:

```php
/**<enter>
function foo() : \DateTime {
}
```

results in:

```php
/**
 * [foo description]
 * @return DateTime [description]
 */
function foo() : \DateTime {
}
```

The \ has been removed, but it is catch by the regex. Do you have any ideas about this?

**Comment by MoritzKn** [comment]
Seems to be the same as in #114. I looked over it and this is probably because the `snippets_service` (which is used to insert the comments) uses backslashes as escape character.  If you like, I would really appreciate if you could fix this.

Anyway that is another thing. I will merge your PR.

**Comment by MoritzKn** [comment]
Merged via cli because RPs should be merged into the develop branch and github doesn't allow to change the branch of a PR.
See: [078c15](https://github.com/nikhilkalige/docblockr/commit/078c159327a88a8702aa1ec5a0f39e363c41b317)

**Comment by MoritzKn** [comment]
> If you like, I would really appreciate if you could fix this.
Sorry forget it, #149 already addresses this.

**Comment by Cronos87** [comment]
Thank you for the merged! And it's perfect if the issue with params is already fixed!

Thanks for the work.

**Pull request closed without merging**
